BOX_BASE = "ubuntu/xenial64"
BOX_RAM_MB = "2048"
BOX_CPU_COUNT = "2"
NAT_DNS_RESOLVER = "on"

Vagrant.configure("2") do |config|
    config.vm.define "lxd1" do |lxd1|
        lxd1.vm.hostname = "lxd1"
        lxd1.vm.box = BOX_BASE

        lxd1.vm.network :private_network, ip: "192.168.56.99"
        lxd1.vm.network :forwarded_port, guest: 8443, host: 8443

        lxd1.vm.provider :virtualbox do |vbox|
            vbox.customize ["modifyvm", :id, "--natdnshostresolver1", NAT_DNS_RESOLVER]
            vbox.customize ["modifyvm", :id, "--memory", BOX_RAM_MB]
            vbox.customize ["modifyvm", :id, "--cpus", BOX_CPU_COUNT]
            vbox.customize ["modifyvm", :id, "--name", "lxd1"]
        end

        lxd1.vm.provision "shell", path: "provision.sh"
        lxd1.vm.provision "file", source: "container-profile.yaml", destination: "container-profile.yaml"
    end

    config.vm.define "lxd2" do |lxd2|
        lxd2.vm.hostname = "lxd2"
        lxd2.vm.box = BOX_BASE

        lxd2.vm.network :private_network, ip: "192.168.56.100"

        lxd2.vm.provider :virtualbox do |vbox|
            vbox.customize ["modifyvm", :id, "--natdnshostresolver1", NAT_DNS_RESOLVER]
            vbox.customize ["modifyvm", :id, "--memory", BOX_RAM_MB]
            vbox.customize ["modifyvm", :id, "--cpus", BOX_CPU_COUNT]
            vbox.customize ["modifyvm", :id, "--name", "lxd2"]
        end

        lxd2.vm.provision "shell", path: "provision.sh"
    end
end