BOX_BASE = "ubuntu/xenial64"
BOX_RAM_MB = "1024"
BOX_CPU_COUNT = "1"
NAT_DNS_RESOLVER = "on"

Vagrant.configure("2") do |config|
    config.vm.define "rkt" do |rkt|
        rkt.vm.hostname = "rkt-host"
        rkt.vm.box = BOX_BASE

        rkt.vm.network :forwarded_port, guest: 8200, host: 8200
        rkt.vm.network :forwarded_port, guest: 8500, host: 8500

        rkt.vm.provider :virtualbox do |vbox|
            vbox.customize ["modifyvm", :id, "--natdnshostresolver1", NAT_DNS_RESOLVER]
            vbox.customize ["modifyvm", :id, "--memory", BOX_RAM_MB]
            vbox.customize ["modifyvm", :id, "--cpus", BOX_CPU_COUNT]
            vbox.customize ["modifyvm", :id, "--name", "rkt-host"]
        end

        rkt.vm.provision "file", source: "build-consul.sh", destination: "build-consul.sh"
        rkt.vm.provision "file", source: "build-vault.sh", destination: "build-vault.sh"
        rkt.vm.provision "file", source: "initialize-vault.sh", destination: "initialize-vault.sh"
        rkt.vm.provision "file", source: "consul-vault-pod.json", destination: "consul-vault-pod.json"
        rkt.vm.provision "file", source: "vault-configs", destination: "vault-configs"
        rkt.vm.provision "file", source: "gpg-batch", destination: "gpg-batch"
        rkt.vm.provision "file", source: "consul-vault.service", destination: "consul-vault.service"
        rkt.vm.provision "file", source: "cleanup.sh", destination: "cleanup.sh"
        rkt.vm.provision "shell", path: "provision.sh"
    end

end