Vagrant.configure("2") do |config|  
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "container-host"
  config.vm.provider "virtualbox"
  config.vm.network :forwarded_port, guest: 8443, host: 8443

  config.vm.provision "shell", path: "provision.sh", privileged: false
end