BOX_BASE = "ubuntu/xenial64"
BOX_RAM_MB = "2048"
BOX_CPU_COUNT = "2"
NAT_DNS_RESOLVER = "on"

Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
        master.vm.hostname = "master"
        master.vm.box = BOX_BASE

        master.vm.network :private_network, ip: "192.168.56.101"
        master.vm.network :forwarded_port, guest: 30000, host: 30000
        master.vm.network :forwarded_port, guest: 31000, host: 31000
        master.vm.network :forwarded_port, guest: 32000, host: 32000

        master.vm.provider :virtualbox do |vbox|
            vbox.customize ["modifyvm", :id, "--natdnshostresolver1", NAT_DNS_RESOLVER]
            vbox.customize ["modifyvm", :id, "--memory", BOX_RAM_MB]
            vbox.customize ["modifyvm", :id, "--cpus", BOX_CPU_COUNT]
            vbox.customize ["modifyvm", :id, "--name", "master"]
        end

        master.vm.provision "shell", path: "provision.sh"
        master.vm.provision "file", source: "manifests", destination: "manifests"
    end

    config.vm.define "worker" do |worker|
        worker.vm.hostname = "worker"
        worker.vm.box = BOX_BASE

        worker.vm.network :private_network, ip: "192.168.56.102"

        worker.vm.provider :virtualbox do |vbox|
            vbox.customize ["modifyvm", :id, "--natdnshostresolver1", NAT_DNS_RESOLVER]
            vbox.customize ["modifyvm", :id, "--memory", BOX_RAM_MB]
            vbox.customize ["modifyvm", :id, "--cpus", BOX_CPU_COUNT]
            vbox.customize ["modifyvm", :id, "--name", "worker"]
        end

        worker.vm.provision "shell", path: "provision.sh"
    end
end
