apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 2
  selector:
    matchLabels:
        app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost
        ports:
        - containerPort: 2368
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  selector:
    app: ghost
  ports:
  - port: 2368
    nodePort: 30000
    protocol: TCP
    name: http
  type: NodePort